baseURL = 'https://ronindev.ninja/'
copyright = 'Bushidolabs LLC All rights reserved.'
languageCode = 'en-us'
title = 'Ronindev'
enableEmoji = true
enableRobotsTXT= true

defaultContentLanguage = "en"
[languages]
  [languages.en]
    languageCode = "en"
    weight = 1
  [languages.es]
    languageCode = "es"
    weight = 2

[params]
	logo = "/images/logo-without-text.webp"
	favicon = "/images/favicon.ico"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    [menu.main.params]
      icon = "icons/home.html"

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
    [menu.main.params]
      icon = "icons/important.html"

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
    [menu.main.params]
      icon = "icons/portfolio.html"

  [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 4
    [menu.main.params]
      icon = "icons/square.html"

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
    [menu.main.params]
      icon = "icons/indicator.html"

	[[menu.footer]]
    name = "X"
    url = "https://x.com/Hackemateninja"
    weight = 1
    [menu.footer.params]
      icon = "icons/x.html"

	[[menu.footer]]
    name = "YouTube"
    url = "https://www.youtube.com/c/hackemateninja"
    weight = 2
    [menu.footer.params]
      icon = "icons/youtube.html"

	[[menu.footer]]
    name = "Github"
    url = "https://github.com/hackemateninja"
    weight = 3
    [menu.footer.params]
      icon = "icons/github.html"

	[[menu.footer]]
    name = "Email"
    url = "/contact/"
    weight = 4
    [menu.footer.params]
      icon = "icons/airplaine.html"


[module]
  [module.hugoVersion]
    extended = true
    min      = "0.128.0"
	[[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/alpinejs"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"
